name: 'Check AWS Inspector'
description: 'Check findings of an aws inspector scan'
branding:
  icon: 'search'
  color: 'red'

inputs:
  repository:
    description: 'Repository name'
    required: true
  registryId:
    description: 'Registry id (aws account id of ecr repository)'
    required: false
  tag:
    description: 'Tag of scanned image'
    required: true
  fail-on: 
    description: 'The unacceptable severity of any scanned vulnerabilities'
  ignore: 
    description: 'The vulnerabilities to ignore'
  timeout:
    description: 'Time in seconds before timing out when polling for scan complete status'
    required: true
  consistency-delay:
    description: 'Time in seconds between subsequent attempts to retrieve consistent scan findings'
    required: true
  poll-rate:
    description: 'Time in seconds between polling attempts when scan is pending or in progress.'
    required: false
    default: 5

outputs:
  findingSeverityCounts:
    description: 'Counts of scanned vulnerabilities grouped by severity'

runs:
  using: 'node16'
  main: 'dist/index.js'
